services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: inquiro_qdrant
    ports:
      - "6333:6333"  
      - "6334:6334"  
    volumes:
      - inquiro_qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    networks:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:6.0-jammy
    container_name: inquiro_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - inquiro_mongodb:/data/db
    networks:
      - backend
    restart: 
      always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:

volumes:
  inquiro_qdrant:
  inquiro_mongodb:
